/home/p_gnngw/miniconda3/envs/cuda118/lib/python3.12/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
Traceback (most recent call last):
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 322, in <module>
    main()
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 315, in main
    val_loss = run(args)
               ^^^^^^^^^
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 158, in run
    train_set = datasets.TSPDataset(args.data_dir / 'train.txt')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/p_gnn001/code/tsp/tsp/gnngls/datasets.py", line 164, in __init__
    directed_string_graph(G)
  File "/project/p_gnn001/code/tsp/tsp/gnngls/datasets.py", line 64, in directed_string_graph
    G2 = dgl.DGLGraph({})
         ^^^^^^^^^^^^^^^^
  File "/home/p_gnngw/miniconda3/envs/cuda118/lib/python3.12/site-packages/dgl/heterograph.py", line 96, in __init__
    (sparse_fmt, arrays), num_src, num_dst = utils.graphdata2tensors(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/p_gnngw/miniconda3/envs/cuda118/lib/python3.12/site-packages/dgl/utils/data.py", line 223, in graphdata2tensors
    raise DGLError("Unsupported graph data type:", type(data))
dgl._ffi.base.DGLError: ('Unsupported graph data type:', <class 'dict'>)
