Traceback (most recent call last):
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 322, in <module>
    main()
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 315, in main
    val_loss = run(args)
               ^^^^^^^^^
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 158, in run
    train_set = datasets.TSPDataset(args.data_dir / 'train.txt')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/p_gnn001/code/tsp/tsp/gnngls/datasets.py", line 163, in __init__
    directed_string_graph(G)
  File "/project/p_gnn001/code/tsp/tsp/gnngls/datasets.py", line 63, in directed_string_graph
    G1.add_nodes(m)
    ^^^^^^^^^^^^
AttributeError: 'Graph' object has no attribute 'add_nodes'. Did you mean: 'add_node'?
